### GET request to example server
GET https://api.sunflower-land.com/collection/collectibles/201?type=collectibles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZGRyZXNzIjoiMHgxNzIxNDIwOWNCNmUxNzBiMjE3RDQzZDNmRjA2MDk1RTdhZDZFMmREIiwidXNlckFjY2VzcyI6eyJzeW5jIjp0cnVlLCJ3aXRoZHJhdyI6dHJ1ZSwibWludENvbGxlY3RpYmxlIjp0cnVlLCJjcmVhdGVGYXJtIjp0cnVlLCJ2ZXJpZmllZCI6dHJ1ZX0sImZhcm1JZCI6NzU4OTY5MjI2ODk3NTQ4MiwiaWF0IjoxNzQ2MzA3NjE0LCJleHAiOjE3NDg4OTk2MTR9.2rLcF6C67AUPUcEV5f0Fpdx41w9zP6fHoS7CUHwMmz0

###

